CREATE TABLE `books` (
                         `id` int NOT NULL AUTO_INCREMENT,
                         `Title` TEXT DEFAULT NULL,
                         `Original Title` TEXT DEFAULT NULL,
                         `Subtitle` TEXT DEFAULT NULL,
                         `Series` TEXT DEFAULT NULL,
                         `Volume` TEXT DEFAULT NULL,
                         `Author` TEXT DEFAULT NULL,
                         `Author (Last First)` TEXT DEFAULT NULL,
                         `Illustrator` TEXT DEFAULT NULL,
                         `Narrator` TEXT DEFAULT NULL,
                         `Translator` TEXT DEFAULT NULL,
                         `Photographer` TEXT DEFAULT NULL,
                         `Editor` TEXT DEFAULT NULL,
                         `Publisher` TEXT DEFAULT NULL,
                         `Place of Publication` TEXT DEFAULT NULL,
                         `Date Published` TEXT DEFAULT NULL,
                         `Year Published` TEXT DEFAULT NULL,
                         `Original Date Published` TEXT DEFAULT NULL,
                         `Original Year Published` TEXT DEFAULT NULL,
                         `Edition` TEXT DEFAULT NULL,
                         `Genre` TEXT DEFAULT NULL,
                         `Summary` TEXT DEFAULT NULL,
                         `Guided Reading Level` TEXT DEFAULT NULL,
                         `Lexile Measure` TEXT DEFAULT NULL,
                         `Lexile Code` TEXT DEFAULT NULL,
                         `Grade Level Equivalent` TEXT DEFAULT NULL,
                         `Developmental Reading Assessment` TEXT DEFAULT NULL,
                         `Interest Level` TEXT DEFAULT NULL,
                         `AR Level` TEXT DEFAULT NULL,
                         `AR Points` TEXT DEFAULT NULL,
                         `AR Quiz Number` TEXT DEFAULT NULL,
                         `Word Count` TEXT DEFAULT NULL,
                         `Number of Pages` TEXT DEFAULT NULL,
                         `Format` TEXT DEFAULT NULL,
                         `Audio Runtime` TEXT DEFAULT NULL,
                         `Dimensions` TEXT DEFAULT NULL,
                         `Weight` TEXT DEFAULT NULL,
                         `List Price` TEXT DEFAULT NULL,
                         `Language` TEXT DEFAULT NULL,
                         `Original Language` TEXT DEFAULT NULL,
                         `DDC` TEXT DEFAULT NULL,
                         `LCC` TEXT DEFAULT NULL,
                         `LCCN` TEXT DEFAULT NULL,
                         `OCLC` TEXT DEFAULT NULL,
                         `ISBN` TEXT DEFAULT NULL,
                         `ISSN` TEXT DEFAULT NULL,
                         `Favorites` TEXT DEFAULT NULL,
                         `Rating` TEXT DEFAULT NULL,
                         `Physical Location` TEXT DEFAULT NULL,
                         `Status` TEXT DEFAULT NULL,
                         `Status Incompleted Reason` TEXT DEFAULT NULL,
                         `Status Hidden` TEXT DEFAULT NULL,
                         `Date Started` TEXT DEFAULT NULL,
                         `Date Finished` TEXT DEFAULT NULL,
                         `Current Page` TEXT DEFAULT NULL,
                         `Loaned To` TEXT DEFAULT NULL,
                         `Date Loaned` TEXT DEFAULT NULL,
                         `Borrowed From` TEXT DEFAULT NULL,
                         `Date Borrowed` TEXT DEFAULT NULL,
                         `Returned from Borrow` TEXT DEFAULT NULL,
                         `Not Owned Reason` TEXT DEFAULT NULL,
                         `Quantity` TEXT DEFAULT NULL,
                         `Condition` TEXT DEFAULT NULL,
                         `Recommended By` TEXT DEFAULT NULL,
                         `Date Added` TEXT DEFAULT NULL,
                         `User Supplied ID` TEXT DEFAULT NULL,
                         `User Supplied Descriptor` TEXT DEFAULT NULL,
                         `Tags` TEXT DEFAULT NULL,
                         `Purchase Date` TEXT DEFAULT NULL,
                         `Purchase Place` TEXT DEFAULT NULL,
                         `Purchase Price` TEXT DEFAULT NULL,
                         `Notes` TEXT DEFAULT NULL,
                         `Google VolumeID` TEXT DEFAULT NULL,
                         `Category` TEXT DEFAULT NULL,
                         `Wish List` TEXT DEFAULT NULL,
                         `Previously Owned` TEXT DEFAULT NULL,
                         `Up Next` TEXT DEFAULT NULL,
                         `Position` TEXT DEFAULT NULL,
                         `Uploaded Image URL` TEXT DEFAULT NULL,
                         `Activities` TEXT DEFAULT NULL,
                         PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci